### ISSUE TITLE
Sidebar Navigation Issues

### ISSUE THREAD

**Issue by zimalshahriar** [asamamun/tigercommerce#1]
**Description:**
The sidebar in the admin panel has a few navigational problems that need to be addressed:

1. **Collapsed Sidebar Issues:** The sidebar collapses unnecessarily on larger screens, which creates navigation difficulties. Since this is an admin panel, the sidebar links should always remain visible to make navigation smoother for users.
   
2. **Navigation Flow:** The current flow of the navigation links isn't as intuitive as it could be. The positioning and arrangement of certain links may confuse users, especially when switching between categories like "Users", "Vendors", and "Orders".
   
3. **Click Detection:** There are instances where clicking on a sidebar link doesn't properly register, causing the navigation to be unresponsive. This could be a result of improper handling of the `collapse` feature or other JavaScript-related issues.
   
4. **Mobile Navigation:** When viewed on mobile, the sidebar links are difficult to access due to alignment and spacing issues. The sidebar does not collapse neatly, making it hard for users to navigate between sections smoothly.

---

**Reason for Not Fixing:**
I’m currently focused on finalizing the main functionalities of the admin panel, such as category, user, vendor, product, and order management. Once these core features are stabilized, I will address the sidebar navigation issues.

---

**Steps to Reproduce:**
1. Load the admin panel with the sidebar.
2. Try collapsing and expanding the sidebar on both large and small screens.
3. Click on different sidebar links (e.g., "Categories", "Users", "Orders") and observe any issues with responsiveness or flow.
4. Resize the window to mobile dimensions and try navigating the sidebar.

---

**Proposed Fix (for Future Iteration):**
- Disable the `collapse` functionality on larger screens to keep the sidebar visible at all times.
- Reorganize the navigation links for better flow and usability.
- Fix any click detection issues that prevent smooth navigation.
- Optimize the sidebar’s design for mobile devices, ensuring proper alignment and spacing for easy navigation.

**Comment by asamamun** [comment]
fixed
